"""baseline schema (subreddit_profile, user_memory, investigation, evidence, feedback, audit_log)

Revision ID: 9b18ae1ccc14
Revises: 
Create Date: 2026-05-13 18:29:19.243111
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b18ae1ccc14'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_correlation', 'audit_log', ['correlation_id'], unique=False)
    op.create_index('ix_audit_log_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_index('ix_audit_log_subreddit_time', 'audit_log', ['subreddit_id', 'created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=20), nullable=False),
    sa.Column('mod_action', sa.String(length=16), nullable=False),
    sa.Column('raw_action', sa.String(length=32), nullable=False),
    sa.Column('moderator_id', sa.String(length=20), nullable=False),
    sa.Column('moderator_name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('aligned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mod_action IN ('REMOVE','APPROVE','ESCALATE','LOCK')", name='ck_feedback_mod_action'),
    sa.CheckConstraint("source IN ('verdict_card','reddit_native')", name='ck_feedback_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_correlation', 'feedback', ['correlation_id'], unique=False)
    op.create_index('ix_feedback_subreddit', 'feedback', ['subreddit_id'], unique=False)
    op.create_index('ix_feedback_target', 'feedback', ['target_id'], unique=False)
    op.create_table('subreddit_profile',
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('personality', sa.String(length=16), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('cold_start_count', sa.Integer(), nullable=False),
    sa.Column('calibration_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('show_cost_in_dashboard', sa.Boolean(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('tier_override', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("personality IN ('strict','balanced','lenient')", name='ck_subreddit_profile_personality'),
    sa.CheckConstraint("region IN ('US','EU','UK','IN','Global')", name='ck_subreddit_profile_region'),
    sa.CheckConstraint("tier_override IN ('auto','fast','standard','deep')", name='ck_subreddit_profile_tier_override'),
    sa.PrimaryKeyConstraint('subreddit_id')
    )
    op.create_table('investigation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.String(length=20), nullable=False),
    sa.Column('target_body', sa.Text(), nullable=False),
    sa.Column('target_author_id', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=True),
    sa.Column('recommendation', sa.String(length=32), nullable=True),
    sa.Column('calibrated_confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_reasoner', sa.String(length=64), nullable=False),
    sa.Column('model_summarizer', sa.String(length=64), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('validation_flag', sa.Boolean(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('cold_start', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("recommendation IS NULL OR recommendation IN ('REMOVE','APPROVE','ESCALATE','LOCK','NO_RECOMMENDATION')", name='ck_investigation_recommendation'),
    sa.CheckConstraint("risk_tier IS NULL OR risk_tier IN ('HIGH','MEDIUM','LOW')", name='ck_investigation_risk_tier'),
    sa.CheckConstraint("status IN ('pending','completed','failed')", name='ck_investigation_status'),
    sa.CheckConstraint("target_kind IN ('comment','post')", name='ck_investigation_target_kind'),
    sa.CheckConstraint("tier IN ('FAST','STANDARD','DEEP')", name='ck_investigation_tier'),
    sa.CheckConstraint('calibrated_confidence IS NULL OR (calibrated_confidence >= 0 AND calibrated_confidence <= 1)', name='ck_investigation_confidence_range'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddit_profile.subreddit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    op.create_index('ix_investigation_correlation', 'investigation', ['correlation_id'], unique=False)
    op.create_index('ix_investigation_subreddit', 'investigation', ['subreddit_id'], unique=False)
    op.create_index('ix_investigation_target', 'investigation', ['target_id'], unique=False)
    op.create_table('user_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('prior_violations', sa.Integer(), nullable=False),
    sa.Column('prior_approvals', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_tier IN ('new','trusted','neutral','watched')", name='ck_user_memory_risk_tier'),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddit_profile.subreddit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subreddit_id', 'user_id', name='uq_user_memory_sub_user')
    )
    op.create_index('ix_user_memory_subreddit', 'user_memory', ['subreddit_id'], unique=False)
    op.create_index('ix_user_memory_user', 'user_memory', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('evidence_id', sa.String(length=16), nullable=False),
    sa.Column('tool', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=280), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success','failure','skipped','timeout')", name='ck_evidence_status'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'evidence_id', name='uq_evidence_investigation_evid')
    )
    op.create_index('ix_evidence_investigation', 'evidence', ['investigation_id'], unique=False)
    op.create_index('ix_evidence_subreddit', 'evidence', ['subreddit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_subreddit', table_name='evidence')
    op.drop_index('ix_evidence_investigation', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_user_memory_user', table_name='user_memory')
    op.drop_index('ix_user_memory_subreddit', table_name='user_memory')
    op.drop_table('user_memory')
    op.drop_index('ix_investigation_target', table_name='investigation')
    op.drop_index('ix_investigation_subreddit', table_name='investigation')
    op.drop_index('ix_investigation_correlation', table_name='investigation')
    op.drop_table('investigation')
    op.drop_table('subreddit_profile')
    op.drop_index('ix_feedback_target', table_name='feedback')
    op.drop_index('ix_feedback_subreddit', table_name='feedback')
    op.drop_index('ix_feedback_correlation', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_audit_log_subreddit_time', table_name='audit_log')
    op.drop_index('ix_audit_log_event_type', table_name='audit_log')
    op.drop_index('ix_audit_log_correlation', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
