"""add thread_memory table

Revision ID: 3274faa44fe9
Revises: 9b18ae1ccc14
Create Date: 2026-05-14 00:00:28.464026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3274faa44fe9'
down_revision: Union[str, None] = '9b18ae1ccc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subreddit_id', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(length=20), nullable=False),
    sa.Column('mod_actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('last_summary', sa.Text(), nullable=False),
    sa.Column('last_summary_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddit_profile.subreddit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subreddit_id', 'post_id', name='uq_thread_memory_sub_post')
    )
    op.create_index('ix_thread_memory_post', 'thread_memory', ['post_id'], unique=False)
    op.create_index('ix_thread_memory_subreddit', 'thread_memory', ['subreddit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thread_memory_subreddit', table_name='thread_memory')
    op.drop_index('ix_thread_memory_post', table_name='thread_memory')
    op.drop_table('thread_memory')
    # ### end Alembic commands ###
